background = [
    "The CITING sentences mention results from the CITED paper to support background claims.",
    "The CITING sentences mention a technique of the CITED paper in order to provide relevant background context.",
    "The CITING sentences mention performance results of the CITED paper to contextualize the CITED model's capabilities.",
    "The CITING authors describe other researchers using the CITED foundation models.",
    "The CITING authors use the CITED foundation models to note a similarity or difference to an existing method.",
    "It's ambiguous as to whether or not the CITING authors actually use the CITED foundation model based on the wording."
]
uses = [
    "The CITING authors deploy the CITED foundation model's encoder or decoder as part of their methodology.",
    "The CITING authors use the CITED foundation model to create embeddings as part of their methodology.",
    "The CITING authors use the CITED foundation model for feature extraction as part of their methodology.",
    "The CITING authors use the CITED foundation model as a classifier or detector as part of their methodology.",
    "The CITING authors deploy the CITED foundation model to generate data in the form of text/image/audio/video for later training of their model.",
    "The CITING authors perform their own evaluation on the CITED foundation model.",
    "The CITING authors perform an ablation study on the CITED foundation model.",
    "The CITING authors clearly deploy the CITED foundation model at some point throughout their methodology."
]

extends = [
    "It's unclear whether or not the CITING authors perform any training on the CITED foundation model.",
    "The CITING authors deploy fine-tuning or adjusting the parameter weights of the CITED foundation model.",
    "The CITING authors pre-train or train-from-scratch the CITED model as part of their methodology.",
    "The CITING authors mention fine-tuning the CITED foundation model as a possibility, but do not mention fine-tuning themselves.",
    "The CITING authors use notable compute resources to traing the CITED foundation model futher.",
]

extra = [
    "The CITING authors train a model using the CITED paper's dataset.",
    "The CITING authors adopt the CITED foundation model's architecture as part of their model design."
    ]

manual = background + uses + extends + extra

generated = manual + [
    "The CITING authors use the CITED foundation model to perform transfer learning.",
    "The CITING authors use the CITED foundation model as a benchmark for comparison.",
    "The CITING authors report improvements achieved by using the CITED foundation model over other models.",
    "The CITING authors integrate the CITED foundation model with other models or algorithms.",
    "The CITING authors use the CITED foundation model to validate a hypothesis or experimental setup.",
    "The CITING authors conduct a qualitative analysis involving the CITED foundation model.",
    "The CITING authors conduct a quantitative analysis involving the CITED foundation model.",
    "The CITING authors highlight limitations or challenges of using the CITED foundation model.",
    "The CITING authors discuss future work or potential extensions involving the CITED foundation model.",
    "The CITING authors leverage the CITED foundation model for a specific application domain (e.g., healthcare, finance, NLP).",
    "The CITING authors mention modifications or adaptations made to the CITED foundation model.",
    "The CITING authors deploy the CITED foundation model in a real-world scenario or experiment.",
    "The CITING authors use the CITED foundation model to perform anomaly detection.",
    "The CITING authors use the CITED foundation model to perform sentiment analysis.",
    "The CITING authors use the CITED foundation model for unsupervised learning tasks.",
    "The CITING authors use the CITED foundation model for supervised learning tasks.",
    "The CITING authors use the CITED foundation model for reinforcement learning tasks.",
    "The CITING authors use the CITED foundation model to process multi-modal data.",
    "The CITING authors use the CITED foundation model to enhance interpretability or explainability of their results.",
    "The CITING authors employ the CITED foundation model to optimize hyperparameters in their experiments.",
    "The CITING authors fine-tune the CITED foundation model on a domain-specific dataset.",
    "The CITING authors mention using a smaller learning rate specifically for fine-tuning the CITED foundation model.",
    "The CITING authors use the CITED foundation model's pre-trained weights as initialization for their own model.",
    "The CITING authors employ transfer learning techniques involving the CITED foundation model.",
    "The CITING authors use the CITED foundation model to pre-train a model before fine-tuning on a specific task.",
    "The CITING authors report using a specific dataset for fine-tuning the CITED foundation model.",
    "The CITING authors mention the number of epochs or iterations used for fine-tuning the CITED foundation model.",
    "The CITING authors discuss the computational resources needed for fine-tuning the CITED foundation model.",
    "The CITING authors mention specific hyperparameters adjusted during the fine-tuning of the CITED foundation model.",
    "The CITING authors compare results between pre-trained and fine-tuned versions of the CITED foundation model.",
    "The CITING authors mention the use of regularization techniques during the fine-tuning of the CITED foundation model.",
    "The CITING authors evaluate the CITED foundation model's performance before and after fine-tuning.",
    "The CITING authors describe modifying the architecture of the CITED foundation model prior to fine-tuning.",
    "The CITING authors report the impact of fine-tuning on the CITED foundation model's generalization ability.",
    "The CITING authors use the CITED foundation model in a semi-supervised learning framework involving fine-tuning.",
    "The CITING authors discuss challenges faced during the fine-tuning of the CITED foundation model.",
    "The CITING authors use data augmentation techniques in conjunction with fine-tuning the CITED foundation model.",
    "The CITING authors mention training the CITED foundation model on a multi-task learning setup.",
    "The CITING authors use the CITED foundation model to initialize another model which is then fine-tuned.",
    "The CITING authors highlight improvements in task performance due to fine-tuning the CITED foundation model."
    ]

extends_tentative = [
    "Do the authors mention any training of the model?",
    "Is there any indication that the model has been fine-tuned?",
    "Do the authors discuss additional training of the model?",
    "Is there any mention of re-training the model?",
    "Do the authors provide details on using computational resources for training?",
    "Is there any discussion of data used for training?",
    "Do the authors mention training steps or processes?",
    "Is there any mention of improving or updating the model through training?",
    "Do the authors describe changing any parameters of the model?",
    "Is there any mention of training from scratch?",
    "Do the authors discuss using pre-trained models?",
    "Is there any mention of refining the model's performance?",
    "Do the authors provide details on training duration?",
    "Is there any mention of training difficulties or challenges?",
    "Do the authors discuss the results of training?",
    "Is there any mention of optimizing the model through training?",
    "Do the authors describe any techniques used during training?",
    "Is there any mention of using new data for training?",
    "Do the authors provide details on the environment used for training?",
    "Is there any mention of resources allocated for training?",
    "Do the authors discuss the training procedure?",
    "Is there any mention of training objectives or goals?",
    "Do the authors provide details on any training outcomes?",
    "Is there any mention of the impact of training on the model?",
    "Do the authors discuss any improvements made through training?",
    "Is there any mention of training strategies?",
    "Do the authors describe any modifications made during training?",
    "Is there any mention of the training process?",
    "Do the authors provide details on training experiments?",
    "Is there any mention of enhancements achieved through training?",
    "Do the authors discuss the training setup?",
    "Is there any mention of using training to adapt the model?",
    "Do the authors describe any updates made through training?",
    "Is there any mention of the training framework?",
    "Do the authors discuss training data?",
    "Is there any mention of training iterations or cycles?",
    "Do the authors provide details on the purpose of training?",
    "Is there any mention of the effectiveness of training?",
    "Do the authors discuss the benefits of training?",
    "Is there any mention of the scope of training?"
]

improved_extends = [extends_tentative[i] for i in [1, 31, 6, 26, 5, 29, 17, 32, 11, 21]]

uses_tenative = [
    "The CITING authors deploy the CITED foundation model's encoder or decoder as part of their methodology.",
    "The CITING authors use the CITED foundation model to create embeddings as part of their methodology.",
    "The CITING authors use the CITED foundation model for feature extraction as part of their methodology.",
    "The CITING authors use the CITED foundation model as a classifier or detector as part of their methodology.",
    "The CITING authors deploy the CITED foundation model to generate data in the form of text/image/audio/video for later training of their model.",
    "The CITING authors perform their own evaluation on the CITED foundation model.",
    "The CITING authors perform an ablation study on the CITED foundation model.",
    "The CITING authors clearly deploy the CITED foundation model at some point throughout their methodology.",
    "The CITING authors fine-tune the CITED foundation model as part of their methodology.",
    "The CITING authors adapt the CITED foundation model to a specific task as part of their methodology.",
    "The CITING authors use transfer learning techniques involving the CITED foundation model.",
    "The CITING authors incorporate the CITED foundation model into their pipeline.",
    "The CITING authors use the CITED foundation model for data augmentation.",
    "The CITING authors combine the CITED foundation model with other models or methods.",
    "The CITING authors use the CITED foundation model for pre-processing data.",
    "The CITING authors compare their results with those obtained using the CITED foundation model.",
    "The CITING authors use the CITED foundation model to initialize their own model.",
    "The CITING authors report improvements due to the use of the CITED foundation model.",
    "The CITING authors replace a component of their model with the CITED foundation model.",
    "The CITING authors use the CITED foundation model to generate synthetic data.",
    "The CITING authors benchmark their model against the CITED foundation model.",
    "The CITING authors report hyperparameters specific to the CITED foundation model.",
    "The CITING authors use the CITED foundation model's architecture for their own model.",
    "The CITING authors utilize pretrained weights from the CITED foundation model.",
    "The CITING authors retrain the CITED foundation model on their own dataset.",
    "The CITING authors modify the CITED foundation model's architecture for their purposes.",
    "The CITING authors use the CITED foundation model's outputs as inputs to their own model.",
    "The CITING authors incorporate the CITED foundation model into their experimental setup.",
    "The CITING authors report limitations or issues with the CITED foundation model.",
    "The CITING authors discuss the CITED foundation model's performance on their tasks.",
    "The CITING authors highlight the CITED foundation model's contribution to their results.",
    "The CITING authors describe the integration of the CITED foundation model into their workflow.",
    "The CITING authors use the CITED foundation model to enhance the performance of their own model.",
    "The CITING authors analyze the CITED foundation model's outputs for their application.",
    "The CITING authors deploy the CITED foundation model for downstream tasks.",
    "The CITING authors use the CITED foundation model in a zero-shot learning setting.",
    "The CITING authors use the CITED foundation model for multi-task learning.",
    "The CITING authors evaluate the robustness of the CITED foundation model.",
    "The CITING authors perform cross-validation involving the CITED foundation model.",
    "The CITING authors report using specific tools or libraries associated with the CITED foundation model."
]

improved_uses = [uses_tenative[i] for i in [27, 11, 30, 7, 18, 20, 15, 36, 23, 21]]



strange_mix_but_currently_best_performing = [
    "The CITING authors deploy the CITED foundation model's encoder or decoder as part of their methodology.",
    "The CITING authors use the CITED foundation model to create embeddings as part of their methodology.",
    "The CITING authors use the CITED foundation model for feature extraction as part of their methodology.",
    "The CITING authors use the CITED foundation model as a classifier or detector as part of their methodology.",
    "The CITING authors deploy the CITED foundation model to generate data in the form of text/image/audio/video for later training of their model.",
    "The CITING authors perform their own evaluation on the CITED foundation model.",
    "The CITING authors perform an ablation study on the CITED foundation model.",
    "The CITING authors clearly deploy the CITED foundation model at some point throughout their methodology.",
    "The CITING authors compare their results against those obtained using the CITED foundation model.",
    "The CITING authors use the CITED foundation model for data preprocessing.",
    "The CITING authors fine-tune the CITED foundation model on their own dataset.",
    "The CITING authors incorporate the CITED foundation model into their model pipeline.",
    "The CITING authors reimplement the CITED foundation model from scratch.",
    "The CITING authors use the CITED foundation model's architecture as inspiration for their own model design.",
    "The CITING authors report results obtained directly from the CITED foundation model.",
    "The CITING authors use the CITED foundation model to benchmark their own model.",
    "The CITING authors perform transfer learning using the CITED foundation model.",
    "The CITING authors use the CITED foundation model's pre-trained weights.",
    "The CITING authors modify the CITED foundation model for their specific application.",
    "The CITING authors evaluate the CITED foundation model on a new dataset.",
    "The CITING authors use the CITED foundation model's embeddings as input features for another model.",
    "The CITING authors use the CITED foundation model in a different domain or application than originally intended.",
    "The CITING authors incorporate the CITED foundation model into an ensemble method.",
    "The CITING authors use the CITED foundation model for unsupervised learning tasks.",
    "The CITING authors use the CITED foundation model for supervised learning tasks.",
    "The CITING authors use the CITED foundation model for semi-supervised learning tasks.",
    "The CITING authors use the CITED foundation model for transfer learning tasks.",
    "The CITING authors use the CITED foundation model to initialize another model.",
    "The CITING authors analyze the CITED foundation model's performance on different tasks.",
    "The CITING authors use the CITED foundation model in a multi-task learning setup.",
    "The CITING authors use the CITED foundation model in a reinforcement learning setup.",
    "The CITING authors use the CITED foundation model in a self-supervised learning setup.",
    "The CITING authors use the CITED foundation model to generate synthetic data.",
    "The CITING authors use the CITED foundation model to augment their training data.",
    "The CITING authors use the CITED foundation model for anomaly detection.",
    "The CITING authors use the CITED foundation model for clustering.",
    "The CITING authors use the CITED foundation model for dimensionality reduction.",
    "The CITING authors use the CITED foundation model for natural language understanding tasks.",
    "The CITING authors use the CITED foundation model for natural language generation tasks.",
    "The CITING authors use the CITED foundation model for image classification tasks.",
    "The CITING authors use the CITED foundation model for image generation tasks.",
    "The CITING authors use the CITED foundation model for speech recognition tasks.",
    "The CITING authors use the CITED foundation model for audio generation tasks.",
    "The CITING authors use the CITED foundation model for video classification tasks.",
    "The CITING authors use the CITED foundation model for video generation tasks.",
    "The CITING authors use the CITED foundation model for time series analysis.",
    "The CITING authors use the CITED foundation model for graph analysis.",
    "The CITING authors use the CITED foundation model for recommendation systems.",
    "The CITING authors use the CITED foundation model for sentiment analysis.",
    "The CITING authors use the CITED foundation model for question answering.",
    "The CITING authors use the CITED foundation model for machine translation.",
    "The CITING authors use the CITED foundation model for summarization.",
    "The CITING authors use the CITED foundation model for text classification.",
    "The CITING authors use the CITED foundation model for object detection.",
    "The CITING authors use the CITED foundation model for semantic segmentation.",
    "The CITING authors use the CITED foundation model for instance segmentation.",
    "The CITING authors use the CITED foundation model for pose estimation.",
    "The CITING authors use the CITED foundation model for image captioning."
]


background_tentative = [
    "Do the CITING sentences reference historical performance data from the CITED paper?",
    "Are the CITING sentences providing a summary of the CITED paper's methodology?",
    "Do the CITING authors highlight limitations or critiques of the CITED model?",
    "Are the CITING sentences contrasting the CITED model with other models?",
    "Do the CITING sentences compare the CITED model's accuracy with other models?",
    "Are the CITING sentences discussing the theoretical framework of the CITED model?",
    "Do the CITING authors provide context on the development history of the CITED model?",
    "Are the CITING sentences mentioning the CITED model to support a review of existing literature?",
    "Do the CITING sentences reference benchmarks used by the CITED model?",
    "Are the CITING sentences explaining the CITED model's place within a broader research trend?",
    "Do the CITING authors cite the CITED model to highlight advancements in the field?",
    "Are the CITING sentences referencing the CITED model's contribution to foundational knowledge?",
    "Do the CITING authors use the CITED model to illustrate a common approach?",
    "Are the CITING sentences mentioning the CITED model's architecture for background information?",
    "Do the CITING authors discuss the CITED model's results to set the stage for new research?",
    "Are the CITING sentences discussing the CITED model's performance metrics without implementing it?",
    "Do the CITING authors use the CITED model to explain standard practices?",
    "Are the CITING sentences highlighting previous studies that used the CITED model?",
    "Do the CITING authors compare the CITED model's performance with other state-of-the-art models?",
    "Are the CITING sentences discussing the evolution of the CITED model over time?",
    "Do the CITING authors mention the CITED model as part of a literature review?",
    "Are the CITING sentences using the CITED model to provide historical context?",
    "Do the CITING authors discuss the CITED model's limitations in a review context?",
    "Are the CITING sentences mentioning the CITED model's impact on the field?",
    "Do the CITING authors reference the CITED model's results to frame their own research?",
    "Are the CITING sentences discussing improvements made by the CITED model over previous models?",
    "Do the CITING authors mention the CITED model to highlight a trend in research?",
    "Are the CITING sentences summarizing the key findings of the CITED paper?",
    "Do the CITING authors mention the CITED model to provide a comparative baseline?",
    "Are the CITING sentences discussing the methodology of the CITED paper?",
    "Do the CITING authors reference the CITED model's algorithm without using it?",
    "Are the CITING sentences discussing the theoretical underpinnings of the CITED model?",
    "Do the CITING authors use the CITED model to explain a concept or principle?",
    "Are the CITING sentences mentioning the CITED model's results to support a claim?",
    "Do the CITING authors provide context on the CITED model's relevance to current research?",
    "Are the CITING sentences highlighting the CITED model's role in advancing the field?",
    "Do the CITING authors use the CITED model as a point of reference in a comparison?",
    "Are the CITING sentences discussing the broader implications of the CITED model's findings?",
    "Do the CITING authors cite the CITED model to support an argument about current trends?",
    "Are the CITING sentences mentioning the CITED model's accuracy to contextualize their own results?",
    "Do the CITING authors use the CITED model to describe common practices in the field?",
    "Are the CITING sentences referencing the CITED model to provide background information?",
    "Do the CITING authors discuss the CITED model's significance in a historical context?",
    "Are the CITING sentences summarizing the CITED paper's contributions to the field?",
    "Do the CITING authors use the CITED model to compare with their own approach?",
    "Are the CITING sentences mentioning the CITED model to illustrate a point?",
    "Do the CITING authors discuss the CITED model's role in shaping current methodologies?",
    "Are the CITING sentences using the CITED model to highlight differences with other approaches?",
    "Do the CITING authors reference the CITED model's findings to provide context for their own research?",
    "Are the CITING sentences discussing the CITED model's benchmarks without implementing them?",
    "Do the CITING authors use the CITED model to support a review of relevant literature?",
    "Are the CITING sentences highlighting the CITED model's influence on subsequent research?",
    "Do the CITING authors reference the CITED model's algorithm as a background detail?",
    "Are the CITING sentences mentioning the CITED model's results to frame their own study?",
    "Do the CITING authors discuss the CITED model's impact on the development of new models?",
    "Are the CITING sentences providing an overview of the CITED model's capabilities?",
    "Do the CITING authors use the CITED model to illustrate advancements in the field?",
    "Are the CITING sentences discussing the CITED model's findings in the context of other research?",
    "Do the CITING authors reference the CITED model to explain a background concept?"
]


weighted = improved_uses * 3 + improved_extends * 3

